### ISSUE TITLE
Implement bytes.fromhex

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin#103]
A lot of data in Cardano (public key hashes, validator addresses, etc) are binary but usually displayed in hexadecimal notation.

Opshin should hence let users transform this usual notation to actual bytes  with `bytes.fromhex("...")` as it is done in python most frequently.

Ideally this comes with pre-evaluation of constant terms on the opshin level, so that the (expensive) transformation is not actually done on-chain but at compilation time.

Note: goes well with #365 

> [Bug bounty](https://github.com/OpShin/opshin/blob/main/BUG_BOUNTY.md): 1000 ADA

**Comment by nielstron** [comment]
this is alread covered for constants as part of #139 hence decreases in priority

**Comment by chrissiwaffler** [comment]
just a small comment on this issue as I also would like to use `bytes.fromhex()` in my smart contracts :)

**Comment by nielstron** [comment]
claiming this issue
