### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by SebastianKuppa** [OpShin/opshin#149]
https://github.com/OpShin/opshin/blob/c252101628cc318fdef1616105698750a438885b/examples/smart_contracts/simple_script.py#L52

Hey I am currently learning the code and I saw that the script is set as a datum. I checked the code on line 109 where the function is called and there the script variable is defined as a Script type.

**Comment by nielstron** [comment]
thanks for raising this. Datum in this case is more generic than Script (which is not true btw in most offchain code). I tightened the type definition nontheless
