### ISSUE TITLE
Add a way to distinct between opshin files and normal python files

### ISSUE THREAD

**Issue by chrissiwaffler** [OpShin/opshin#159]
**Is your feature request related to a problem? Please describe.**
Right now, when using the linter, we don't know if the current python file is supposed to be a opshin smart contract.

**Describe the solution you'd like**
Add a way to distinct a python file between a normal one and an opshin smart contract.
Either add a shebang or define a different python ending like “.pyo” for opshin files as previously described [here](https://github.com/OpShin/opshin/pull/157#issuecomment-1550483176) by @nielstron 

**Additional context**
-/-

**Comment by nielstron** [comment]
A quick internet search returned nothing in usable resutls concerning file endings. In any case, I suggest to introduce a shebang-ish style for compatability reason (ideally something that would result in the shebang being a valid command in unix, such that `./validator.py` is correctly executed by opshin)

**Comment by nielstron** [comment]
This also begs the question whether there should be another command for compiling, linting etc besides `spending`etc - which is `lib`, which would simply generate uplc code but does not call a designated validator function

**Comment by chrissiwaffler** [comment]
> such that ./validator.py is correctly executed by opshin, i.e. #! opshin eval any)

I'm facing an issue trying out that solution.
I've added that shebang to a python file, but executing it returns: 
```
usage: opshin [-h] [-o OUTPUT_DIRECTORY] [--force-three-params] [--output-format-json]
              {compile_pluto,compile,eval,parse,eval_uplc,build,lint} {spending,minting,rewarding,certifying,any} input_file [args ...]
opshin: error: argument command: invalid choice: 'eval any' (choose from 'compile_pluto', 'compile', 'eval', 'parse', 'eval_uplc', 'build', 'lint')
```
---
It seems that the arguments after “`opshin`” are **not** split and get passed as one argument instead.

This is also the explanation of [this stackoverflow answer (under number 3)](https://stackoverflow.com/a/4304187/12165405) as a possible way of an OS treating the shebang.

---

### Solution for this
by using the [`-S` flag for the env invocation](https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html#g_t_002dS_002f_002d_002dsplit_002dstring-usage-in-scripts) you can specify to split the arguments by whitespace. 

So after all, a possible shebang-ish first line then could look like: `#!/usr/bin/env -S opshin eval any`.
Unluckily, it isn't that short after all

**Comment by juliusfrost** [comment]
Maybe we could we make a default opshin command. For example make `opshin` equivalent to `opshin eval any`

**Comment by chrissiwaffler** [comment]
I like the idea, but then I think we would lose the option to specify explicitly what type the script is (e.g., spending or minting) instead of using `any`

**Comment by juliusfrost** [comment]
> I like the idea, but then I think we would lose the option to specify explicitly what type the script is (e.g., spending or minting) instead of using `any`

No, this would just be in addition to the existing functionality. So instead of giving the missing argument message it would run that command. But normal usage will still require use of the subcommands and script type.

**Comment by chrissiwaffler** [comment]
Ah I see! Yes that would be nice to have!
