### ISSUE TITLE
Implement support for formatted strings

### ISSUE THREAD

**Issue by chrissiwaffler** [OpShin/opshin#193]
**Is your feature request related to a problem? Please describe.**
Would be nice to do something like: `assert False, f"unexpected purpose {purpose}"`

According to the linter, it is not possible right now: `Cannot infer type of non-implemented node <class 'ast.JoinedStr'>`

---

Would be a nice feature, but is not crucial!

**Comment by nielstron** [comment]
for now you can do "..." + str(x) but stringification is indeed also not implemented yet for everything

**Comment by nielstron** [comment]
closed via #206
