### ISSUE TITLE
Enable decode/str for ByteString

### ISSUE THREAD

**Issue by ross-spencer** [OpShin/opshin#276]
**Is your feature request related to a problem? Please describe.**

I am seeing an error decoding a `ByteString` from a datum. It's unclear why this isn't supported, but it does look like I am asking something of the library that isn't supported.

Error looks like this:

```str
pycardano.exception.TransactionFailedException: {'EvaluationFailure': {'ScriptFailures': {'spend:0': [{'validatorFailed': {'error': "An error has occurred:  User error:\nThe machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.\nCaused by: [\n  (builtin decodeUtf8)\n  (con bytestring #90b121aa6b689200adf7ed115040a96375d2b68e23633d6864c53a91)\n]", 'traces': []}}]}}}
```

But given it is possible to do similar with `str(int)` it'd be great to see some support for the ByteString primitive.

**Describe the solution you'd like**

Enable, `str()` or `__repr__` like functionality on the `ByteString` object.

**Describe alternatives you've considered**

Clearly this may be a limitation I am not understanding so it'd be great to see some additional documentation on decoding limitations. 

**Additional context**

Nope, but looking forward to discussing more.

**Comment by nielstron** [comment]
Could you please share the context in which you are using this? Is there a dataclass definition in which you are using ByteString or somewhere in an OpShin contract?

**Comment by nielstron** [comment]
The error you posted is more likely related to the fact that the string you try to decode is not actually a valid UTF8 encoded value, but the contract still tries to decode it
```
>>> bytes.fromhex("90b121aa6b689200adf7ed115040a96375d2b68e23633d6864c53a91")
b'\x90\xb1!\xaakh\x92\x00\xad\xf7\xed\x11P@\xa9cu\xd2\xb6\x8e#c=hd\xc5:\x91'
```

Are you using `str` as the annotation for an OpShin contract? Did you try `bytes`?

**Comment by ross-spencer** [comment]
@nielstron apologies, yep, that seems to be it. Chasing other bugs they all start to look like bugs eventually. Thanks for the sanity check. Enjoying working with your code! cheers.
