### ISSUE TITLE
Recursion error when automatically converting bool to int

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin#369]
**Describe the bug**
```python
  File "test.py", line 4
    return 1 + (a < b)
          ^
RecursionError: maximum recursion depth exceeded in comparison
Note that opshin errors may be overly restrictive as they aim to prevent code with unintended consequences.
```

**To Reproduce**
```bash
$ cat test.py 
from opshin.prelude import *

def validator(a: bool, b: bool) -> int:
    return 1 + (a < b)
$ opshin build test.py
```

**Expected behavior**
Should not give recursion error.

> [Bug bounty](https://github.com/OpShin/opshin/blob/main/BUG_BOUNTY.md): 200 ADA

**Comment by SCMusson** [comment]
gt and lt binops were not implemented in `type_impls.BoolType`, nor were Add or Sub binops where right hand side was a boolean.
