### ISSUE TITLE
Pycardano 0.11.0 have released!

### ISSUE THREAD

**Issue by thaopt** [OpShin/opshin#376]
Any plan to migrate to new pycardano version? current opshin version required hard version of pycardano = 0.10.0

**Comment by srinmd** [comment]
It should not be an issue to upgrade. Can you maGBE try locally to change the dependencies and check if any unit test fails?

**Comment by nielstron** [comment]
It should not be an issue to upgrade. Can you try locally to change the dependencies and see if any unit test fails?

**Comment by thaopt** [comment]
it required to update pluthon and uplc also, i can update it myself. I have problem with deserialize on pycardano 0.10.0, when update to 0.11.1 the problem solved. can you help me with this upgrade?

**Comment by nielstron** [comment]
Unfortunately it seems that updating pycardano to 0.11.1 is blocked by the current dependency of UPLC depending on pycardano <0.11.0. There are two paths to resolve this

- upgrade opshin to use uplc 1.0.0 (https://github.com/OpShin/opshin/issues/343)
- push a new intermediate version of uplc that works with pycardano 0.11.1

**Comment by nielstron** [comment]
Fixed in `0.21.2`
