### ISSUE TITLE
Implement fractions with class methods i.e. __add__ and __mul__ etc

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin#395]
**Is your feature request related to a problem? Please describe.**
Currently, fraction handling is very tedious, requiring specialized functions like `frac_mul(x, y)` to multiply fractions.

**Describe the solution you'd like**
Since #366 was resolved, it is now possible to implement dunder methods for the `Fractions` class in the fractions std lib - this would allow overwriting the behavior of i.e. `__add__` s.t. `x + y` is valid when x and y are `Fraction`s.

**Describe alternatives you've considered**
None

**Additional context**
None

> [Bug bounty](https://github.com/OpShin/opshin/blob/main/BUG_BOUNTY.md): 300 ADA

**Comment by SCMusson** [comment]
I'll claim this one
