### ISSUE TITLE
Failed to build pyaiken on install

### ISSUE THREAD

**Issue by MikeBorman1** [OpShin/opshin#53]
Failed to install -> had to install Rust which was successful -> now getting a new error as below

Using python 3.8
Windows 11
Venv in pycharm

Not pasted all the 508 errors as they are all similar to below.

`      error[E0425]: cannot find function `_mm256_xor_si256` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:328:9
          |
      328 |     b = _mm256_xor_si256(b, state_b);
          |         ^^^^^^^^^^^^^^^^ not found in this scope
          |
      help: consider importing this function
          |
      1   | use core::arch::x86::_mm256_xor_si256;
          |

      error[E0425]: cannot find function `_mm256_storeu_si256` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:329:5
          |
      329 |     _mm256_storeu_si256(h, a);
          |     ^^^^^^^^^^^^^^^^^^^ not found in this scope
          |
      help: consider importing this function
          |
      1   | use core::arch::x86::_mm256_storeu_si256;
          |

      error[E0425]: cannot find function `_mm256_storeu_si256` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:330:5
          |
      330 |     _mm256_storeu_si256(h.add(1), b);
          |     ^^^^^^^^^^^^^^^^^^^ not found in this scope
          |
      help: consider importing this function
          |
      1   | use core::arch::x86::_mm256_storeu_si256;
          |

      error[E0412]: cannot find type `__m128i` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:334:40
          |
      334 |     let block = buf.as_ptr() as *const __m128i;
          |                                        ^^^^^^^ not found in this scope
          |
      help: consider importing this struct
          |
      1   | use core::arch::x86::__m128i;
          |

      error[E0412]: cannot find type `__m256i` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:335:36
          |
      335 |     let h = h.as_mut_ptr() as *mut __m256i;
          |                                    ^^^^^^^ not found in this scope
          |
      help: consider importing this struct
          |
      1   | use core::arch::x86::__m256i;
          |

      error[E0412]: cannot find type `__m256i` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:336:39
          |
      336 |     let iv = b::IV.as_ptr() as *const __m256i;
          |                                       ^^^^^^^ not found in this scope
          |
      help: consider importing this struct
          |
      1   | use core::arch::x86::__m256i;
          |

      error[E0425]: cannot find function `_mm256_set_epi64x` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:339:13
          |
      339 |             _mm256_set_epi64x(0, -1i64, t[1] as i64, t[0] as i64)
          |             ^^^^^^^^^^^^^^^^^ not found in this scope
          |
      help: consider importing this function
          |
      1   | use core::arch::x86::_mm256_set_epi64x;
          |

      error[E0425]: cannot find function `_mm256_set_epi64x` in this scope
         --> C:\Users\beanb\.cargo\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.4.2\src\hashing\blake2\avx2.rs:341:13
          |
      341 |             _mm256_set_epi64x(0, 0, t[1] as i64, t[0] as i64)
          |             ^^^^^^^^^^^^^^^^^ not found in this scope
          |
      help: consider importing this function
          |
      1   | use core::arch::x86::_mm256_set_epi64x;
          |

      error: aborting due to 508 previous errors

      Some errors have detailed explanations: E0412, E0425.

      For more information about an error, try `rustc --explain E0412`.

      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\Users\\Public\\Documents\\pythonProject1\\venv\\Scripts\\python.exe', '--compatibility', 'off', '--target', 'i686-pc-windows-msvc'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaiken
Failed to build pyaiken
ERROR: Could not build wheels for pyaiken, which is required to install pyproject.toml-based projects
`

**Comment by nielstron** [comment]
Oh wow interesting. This issue actually suggests that @Aiken-eng can not be built on Windows systems 🤔

Unfortunately its currently unfeasible to get Aiken out of the dependencies/make a pure python build. I'll try and see if I can provide a binary for windows. Can you otherwise try to go ahead using the Windows Subsystem for Linux?

**Comment by KtorZ** [comment]
We have got several users building Aiken on Windows without issue. Though the project requires a rather recent version of the rust toolkit.

**Comment by MikeBorman1** [comment]
> We have got several users building Aiken on Windows without issue. Though the project requires a rather recent version of the rust toolkit.

What should I do, I installed the latest version of rust yesterday?

**Comment by nielstron** [comment]
Might also be an architecture issue? @MikeBorman1 what is your processor architecture?

**Comment by MikeBorman1** [comment]
Processor = 	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s) 64-bit operating system, x64-based processor

**Comment by nielstron** [comment]
There have been AVX related commits in the crytoxide repository recently, maybe the version needs to be bumped?

https://github.com/typed-io/cryptoxide/commit/0a5781547d632a3a07a8daf8d78dc31ee3c9162e

**Comment by MikeBorman1** [comment]
Do I need to do something?

**Comment by nielstron** [comment]
Hm I don't think this is easily fixed. Will need to investigate.

For now you can maybe try to install Eopsin without installing pyaiken via
```
pip install eopsin-lang --no-deps
```

Also install all the dependecies otherwise listed in setup.py manually.

You will not be able to use the `build` command then.

**Comment by nielstron** [comment]
@MikeBorman1 if you want ot help us debugging, you can try building https://github.com/typed-io/cryptoxide with the latest release and see if you get the same error. If so, we need to escalate this issue to the builders of cryptoxide.

**Comment by MikeBorman1** [comment]
Yep built a project with cryptoxide all fine. Don't rule out the possibility that I'm doing something really stupid trying to set up eopsin. Its probably a high possibility.

**Comment by nielstron** [comment]
Thanks! Just trying to pin down whats happening.

Can you try checking out this commit/version of cryptoxide and building? 1ecc6299db9ec823 0.4.2


You can of course also share the commands you used to set up the virtualenvironment and install the package, then we can see if anything during installation is off

**Comment by MikeBorman1** [comment]
Seems to work, im new to rust  so maybe check : what im doing is creating a project, 
cargo add cryptoxide
cargo build

I just changed the version to 0.4.2 and that worked too.

For the venv, I created it using pycharm, selecting python 3.8 as the interp, added eopsin, got an error telling me to install rust, did that, then got the erros as pasted above.

**Comment by nielstron** [comment]
Okay @MikeBorman1 I am bumping pyaiken to the new release (0.0.29) of aiken, hopefully that changes anything.

Note that the CI should also deploy pre-built wheels for windows and mac, so make sure to have python wheels installed to avoid having to build everything yourself

**Comment by nielstron** [comment]
Bumped to 0.8.1, please try again :)

**Comment by nielstron** [comment]
This issue should be entirely resolved since version `0.11.0`, which aims to entirely remove Rust dependencies. Please re-open if you encounter the issue again.
