### ISSUE TITLE
Smart Contract Blueprints

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin#57]
As suggested by @KtorZ, eopsin should feature Smart contract blueprints as compilation artifacts.

See the CIP for more info: https://cips.cardano.org/cips/cip57/

**Comment by nielstron** [comment]
Realistically, this depends on #112

**Comment by Ursify** [comment]
Hi Niel,

I'm getting a 404 with your link to CIP 57, after searching it in CIPS page, I can see it is different:
[https://cips.cardano.org/cip/CIP-0057](https://cips.cardano.org/cip/CIP-0057)

Cheers,

**Comment by Ursify** [comment]
> As suggested by @KtorZ, eopsin should feature Smart contract blueprints as compilation artifacts.
> 
> See the CIP for more info: https://cips.cardano.org/cips/cip57/

Hi Niel,

I'm getting a 404 with your link to CIP 57, probably it was updated, after searching it in CIPS page, I can see it is different now:
https://cips.cardano.org/cip/CIP-0057

Cheers,
